/**
 * VikaOne Mutual Fund — Phase 5G Portfolio Source Registry
 * Comprehensive registry covering all 55 AMCs in the customer-facing catalogue.
 * Each entry provides official regulatory & AMC monthly portfolio disclosure URLs,
 * accepted formats, ingestion parsers, and identity matching rules.
 */

const AMC_PORTFOLIO_REGISTRY = {
  HDFC_MF: {
    amcCode: 'HDFC_MF',
    amcName: 'HDFC Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.hdfcfund.com/statutory-disclosure/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'hdfc_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  INVESCO_MF: {
    amcCode: 'INVESCO_MF',
    amcName: 'Invesco Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.invescomutualfund.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'invesco_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  BANDHAN_MF: {
    amcCode: 'BANDHAN_MF',
    amcName: 'Bandhan Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://bandhanmutual.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'bandhan_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  PPFAS_MF: {
    amcCode: 'PPFAS_MF',
    amcName: 'PPFAS Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://amc.ppfas.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'ppfas_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ICICI_PRUDENTIA_MF: {
    amcCode: 'ICICI_PRUDENTIA_MF',
    amcName: 'ICICI Prudential Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.icicipruamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'icici_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ICICI_PRU_MF: {
    amcCode: 'ICICI_PRU_MF',
    amcName: 'ICICI Prudential Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.icicipruamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'icici_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  UTI_MF: {
    amcCode: 'UTI_MF',
    amcName: 'UTI Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.utimf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'uti_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  FRANKLIN_TEMPLE_MF: {
    amcCode: 'FRANKLIN_TEMPLE_MF',
    amcName: 'Franklin Templeton Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.franklintempletonindia.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'franklin_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  SBI_MF: {
    amcCode: 'SBI_MF',
    amcName: 'SBI Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.sbimf.com/en-us/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'sbi_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  KOTAK_MAHINDRA_MF: {
    amcCode: 'KOTAK_MAHINDRA_MF',
    amcName: 'Kotak Mahindra Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://assetmanagement.kotak.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'kotak_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  NIPPON_INDIA_MF: {
    amcCode: 'NIPPON_INDIA_MF',
    amcName: 'Nippon India Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://mf.nipponindiaim.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'nippon_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  NIPPON_MF: {
    amcCode: 'NIPPON_MF',
    amcName: 'Nippon India Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://mf.nipponindiaim.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'nippon_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  AXIS_MF: {
    amcCode: 'AXIS_MF',
    amcName: 'Axis Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.axismf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'axis_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ADITYA_BIRLA_SU_MF: {
    amcCode: 'ADITYA_BIRLA_SU_MF',
    amcName: 'Aditya Birla Sun Life Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://mutualfund.adityabirlacapital.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'absl_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  DSP_MF: {
    amcCode: 'DSP_MF',
    amcName: 'DSP Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.dspim.com/mandatory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'dsp_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  TATA_MF: {
    amcCode: 'TATA_MF',
    amcName: 'Tata Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.tatamutualfund.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'tata_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  EDELWEISS_MF: {
    amcCode: 'EDELWEISS_MF',
    amcName: 'Edelweiss Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.edelweissmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'edelweiss_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  MIRAE_ASSET_MF: {
    amcCode: 'MIRAE_ASSET_MF',
    amcName: 'Mirae Asset Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.miraeassetmf.co.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'mirae_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  BARODA_BNP_PARI_MF: {
    amcCode: 'BARODA_BNP_PARI_MF',
    amcName: 'Baroda BNP Paribas Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.barodabnpparibasmf.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'baroda_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  HSBC_MF: {
    amcCode: 'HSBC_MF',
    amcName: 'HSBC Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.assetmanagement.hsbc.co.in/en/mutual-funds/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'hsbc_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  MOTILAL_OSWAL_MF: {
    amcCode: 'MOTILAL_OSWAL_MF',
    amcName: 'Motilal Oswal Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.motilaloswalmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'motilal_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  GROWW_MF: {
    amcCode: 'GROWW_MF',
    amcName: 'Groww Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://growwmf.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'groww_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  LIC_MF: {
    amcCode: 'LIC_MF',
    amcName: 'LIC Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.licmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'lic_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  SUNDARAM_MF: {
    amcCode: 'SUNDARAM_MF',
    amcName: 'Sundaram Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.sundarammutual.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'sundaram_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  UNION_MF: {
    amcCode: 'UNION_MF',
    amcName: 'Union Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.unionmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'union_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  QUANT_MF: {
    amcCode: 'QUANT_MF',
    amcName: 'quant Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://quantmutual.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'quant_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  BANK_OF_INDIA_MF: {
    amcCode: 'BANK_OF_INDIA_MF',
    amcName: 'Bank of India Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.boimf.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'boi_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  MAHINDRA_MANULI_MF: {
    amcCode: 'MAHINDRA_MANULI_MF',
    amcName: 'Mahindra Manulife Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.mahindramanulife.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'mahindra_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  CANARA_ROBECO_MF: {
    amcCode: 'CANARA_ROBECO_MF',
    amcName: 'Canara Robeco Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.canararobeco.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'canara_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  PGIM_INDIA_MF: {
    amcCode: 'PGIM_INDIA_MF',
    amcName: 'PGIM India Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.pgimindiamf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'pgim_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  BAJAJ_FINSERV_MF: {
    amcCode: 'BAJAJ_FINSERV_MF',
    amcName: 'Bajaj Finserv Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.bajajfinservamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'bajaj_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  WHITEOAK_CAPITA_MF: {
    amcCode: 'WHITEOAK_CAPITA_MF',
    amcName: 'WhiteOak Capital Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://mf.whiteoakamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'whiteoak_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ITI_MF: {
    amcCode: 'ITI_MF',
    amcName: 'ITI Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.itiamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'iti_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  JM_FINANCIAL_MF: {
    amcCode: 'JM_FINANCIAL_MF',
    amcName: 'JM Financial Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.jmfinancialmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'jm_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  NAVI_MF: {
    amcCode: 'NAVI_MF',
    amcName: 'Navi Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://navi.com/mutual-fund/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'navi_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  JIO_BLACKROCK_MF: {
    amcCode: 'JIO_BLACKROCK_MF',
    amcName: 'Jio BlackRock Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.jioblackrock.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'jio_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  QUANTUM_MF: {
    amcCode: 'QUANTUM_MF',
    amcName: 'Quantum Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.quantumamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'quantum_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  SAMCO_MF: {
    amcCode: 'SAMCO_MF',
    amcName: 'Samco Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.samcomf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'samco_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  THE_WEALTH_MF: {
    amcCode: 'THE_WEALTH_MF',
    amcName: 'The Wealth Company Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.wealthcompany.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'wealth_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  TRUST_MF: {
    amcCode: 'TRUST_MF',
    amcName: 'Trust Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.trustmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'trust_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  '360_ONE_MF': {
    amcCode: '360_ONE_MF',
    amcName: '360 ONE Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.iiflmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: '360one_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  SHRIRAM_MF: {
    amcCode: 'SHRIRAM_MF',
    amcName: 'Shriram Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.shrirammf.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'shriram_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  TAURUS_MF: {
    amcCode: 'TAURUS_MF',
    amcName: 'Taurus Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.taurusmutualfund.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'taurus_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  HELIOS_MF: {
    amcCode: 'HELIOS_MF',
    amcName: 'Helios Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.heliosmf.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'helios_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  NJ_MF: {
    amcCode: 'NJ_MF',
    amcName: 'NJ Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.njmutualfund.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'nj_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ABAKKUS_MF: {
    amcCode: 'ABAKKUS_MF',
    amcName: 'Abakkus Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://abakkusinvest.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'abakkus_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ANGEL_ONE_MF: {
    amcCode: 'ANGEL_ONE_MF',
    amcName: 'Angel One Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.angelonemf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'angel_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  CAPITALMIND_MF: {
    amcCode: 'CAPITALMIND_MF',
    amcName: 'Capitalmind Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://mutualfunds.capitalmind.in/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'capitalmind_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  CHOICE_MF: {
    amcCode: 'CHOICE_MF',
    amcName: 'Choice Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.choicemutualfund.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'choice_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  UNIFI_MF: {
    amcCode: 'UNIFI_MF',
    amcName: 'Unifi Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.unificapital.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'unifi_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ALPHAGREP_MF: {
    amcCode: 'ALPHAGREP_MF',
    amcName: 'AlphaGrep Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.alphagrepamc.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'alphagrep_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  OLD_BRIDGE_MF: {
    amcCode: 'OLD_BRIDGE_MF',
    amcName: 'Old Bridge Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.oldbridgemf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'oldbridge_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  LAKSHYA_MF: {
    amcCode: 'LAKSHYA_MF',
    amcName: 'Lakshya Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.lakshyamf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'lakshya_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  MONARCH_MF: {
    amcCode: 'MONARCH_MF',
    amcName: 'Monarch Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.monarchmf.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'monarch_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
  ZERODHA_MF: {
    amcCode: 'ZERODHA_MF',
    amcName: 'Zerodha Mutual Fund',
    portfolioSourceType: 'AMC_MONTHLY_PORTFOLIO',
    sourceURL: 'https://www.zerodhafundhouse.com/statutory-disclosures/monthly-portfolio',
    format: 'XLSX',
    frequency: 'MONTHLY',
    parser: 'zerodha_v1',
    identityRules: { planType: 'REGULAR', option: 'GROWTH' },
    status: 'ACTIVE',
  },
};

class MfPortfolioSourceRegistry {
  constructor() {
    this.registry = AMC_PORTFOLIO_REGISTRY;
  }

  getAmc(code) {
    if (!code) return null;
    return this.registry[code.toUpperCase()] || null;
  }

  getRegistryEntry(code) {
    return this.getAmc(code);
  }

  getAllAmcs() {
    return Object.values(this.registry);
  }

  getAmcCount() {
    return Object.keys(this.registry).length;
  }

  isSupported(code) {
    return !!this.getAmc(code);
  }
}

module.exports = new MfPortfolioSourceRegistry();
