const fs = require('fs');
const path = require('path');

const viewPath = 'C:/Ashahad/Porwal/GoldVikaone/lib/modules/mutual_funds/views/mf_scheme_detail_view.dart';
if (!fs.existsSync(viewPath)) {
  console.error('File not found:', viewPath);
  process.exit(1);
}

let content = fs.readFileSync(viewPath, 'utf8');

// 1. Add _isAboutFundExpanded
if (!content.includes('bool _isAboutFundExpanded')) {
  content = content.replace(
    'bool _isFundHouseExpanded = false;\n  bool _isProsConsExpanded = false;',
    'bool _isFundHouseExpanded = false;\n  bool _isAboutFundExpanded = false;\n  bool _isProsConsExpanded = false;'
  );
  console.log('1. Added _isAboutFundExpanded');
}

// 2. Add holdings getters
if (!content.includes('String? get _holdingsAsOfDate')) {
  const holdingsGetters = [
    '',
    '  String? get _holdingsAsOfDate {',
    "    return _detailData?['holdingsAsOfDate']?.toString() ??",
    "        _detailData?['portfolio']?['holdingsAsOf']?.toString() ??",
    "        '30 Sep 2026';",
    '  }',
    '',
    '  bool get _isPartialHoldings {',
    "    return _detailData?['portfolio']?['isPartial'] == true;",
    '  }',
    '',
    '  int? get _totalHoldingsCount {',
    "    return (_detailData?['portfolio']?['totalHoldingsCount'] as num?)?.toInt();",
    '  }',
  ].join('\n');

  content = content.replace(
    'bool get _hasRealHoldings => _topHoldingsList.isNotEmpty;',
    'bool get _hasRealHoldings => _topHoldingsList.isNotEmpty;' + holdingsGetters
  );
  console.log('2. Added holdings getters');
}

// 3. Update _topHoldingsList to handle real backend holdings payload
const oldHoldingsMarker = 'List<Map<String, dynamic>> get _topHoldingsList {';
const nextMethodMarker = 'bool get _hasRealHoldings => _topHoldingsList.isNotEmpty;';

const newTopHoldingsFn = [
  'List<Map<String, dynamic>> get _topHoldingsList {',
  '    List? list;',
  '    if (_detailData != null) {',
  "      if (_detailData!['holdings'] is List && (_detailData!['holdings'] as List).isNotEmpty) {",
  "        list = _detailData!['holdings'] as List;",
  "      } else if (_detailData!['portfolio'] is Map && _detailData!['portfolio']['holdings'] is List) {",
  "        list = _detailData!['portfolio']['holdings'] as List;",
  "      } else if (_detailData!['topHoldings'] is List && (_detailData!['topHoldings'] as List).isNotEmpty) {",
  "        list = _detailData!['topHoldings'] as List;",
  '      }',
  '    }',
  '    if (list != null && list.isNotEmpty) {',
  '      return list',
  '          .whereType<Map<String, dynamic>>()',
  '          .map((e) {',
  "            final weightNum = (e['weight'] ?? e['percentage']) as num?;",
  "            final weightStr = weightNum != null ? '${weightNum.toStringAsFixed(2)}%' : '—';",
  '            return {',
  "              'name': e['name']?.toString() ?? '',",
  "              'weight': weightStr,",
  "              'sector': e['sector']?.toString() ?? '',",
  "              'isin': e['isin']?.toString() ?? '',",
  "              'assetClass': e['assetClass']?.toString() ?? 'Equity',",
  "              'hasArrow': true,",
  '            };',
  '          })',
  "          .where((h) => (h['name'] as String).isNotEmpty)",
  '          .toList();',
  '    }',
  '    return [];',
  '  }',
  '',
  '  ',
].join('\n');

const holdingsStartIdx = content.indexOf(oldHoldingsMarker);
const holdingsEndIdx = content.indexOf(nextMethodMarker);
if (holdingsStartIdx !== -1 && holdingsEndIdx !== -1) {
  content = content.slice(0, holdingsStartIdx) + newTopHoldingsFn + content.slice(holdingsEndIdx);
  console.log('3. Updated _topHoldingsList');
}

// 4. Update the layout: Replace 2x2 grid with Fund Overview and Investment sections
const oldGridStart = '// ── 2x2 Fund Metrics Grid (Screenshot 4) ──';
const oldGridEnd = '// ── Top Action Links (Screenshot 1) ──';

const newSections = [
  '// ── Fund Overview & Investment Rules (Phase 5D Production Sections) ──',
  '            _buildFundOverviewSection(mintGreen, textSecondary, textPrimary, surface, border),',
  '            const SizedBox(height: 16),',
  '            _buildInvestmentSection(mintGreen, textSecondary, textPrimary, surface, border),',
  '            const SizedBox(height: 20),',
  '            const Divider(color: border, height: 1),',
  '',
  '            ',
].join('\n');

const gridStartIdx = content.indexOf(oldGridStart);
const gridEndIdx = content.indexOf(oldGridEnd);
if (gridStartIdx !== -1 && gridEndIdx !== -1) {
  content = content.slice(0, gridStartIdx) + newSections + content.slice(gridEndIdx);
  console.log('4. Replaced 2x2 grid with Fund Overview & Investment sections');
}

// 5. Update Accordions: Add About the Fund accordion after Fund House
const oldFundHouseAccordion = [
  "            // ── ACCORDION 7: Fund house & investment objective (Screenshot 3) ──",
  "            _buildAccordionHeader(",
  "              title: 'Fund house & investment objective',",
  "              isExpanded: _isFundHouseExpanded,",
  "              onTap: () => setState(() => _isFundHouseExpanded = !_isFundHouseExpanded),",
  "            ),",
  "            if (_isFundHouseExpanded) _buildFundHouseSection(mintGreen, textSecondary, textPrimary),",
  "            const Divider(color: border, height: 1),",
].join('\n');

const newFundHouseAndAboutAccordions = [
  "            // ── ACCORDION 7: Fund house (Phase 5D Decoupled AMC AUM) ──",
  "            _buildAccordionHeader(",
  "              title: 'Fund house',",
  "              isExpanded: _isFundHouseExpanded,",
  "              onTap: () => setState(() => _isFundHouseExpanded = !_isFundHouseExpanded),",
  "            ),",
  "            if (_isFundHouseExpanded) _buildFundHouseSection(mintGreen, textSecondary, textPrimary),",
  "            const Divider(color: border, height: 1),",
  "",
  "            // ── ACCORDION 8: About the fund (Investment objective) ──",
  "            _buildAccordionHeader(",
  "              title: 'About the fund',",
  "              isExpanded: _isAboutFundExpanded,",
  "              onTap: () => setState(() => _isAboutFundExpanded = !_isAboutFundExpanded),",
  "            ),",
  "            if (_isAboutFundExpanded) _buildAboutFundSection(mintGreen, textSecondary, textPrimary),",
  "            const Divider(color: border, height: 1),",
].join('\n');

if (content.includes(oldFundHouseAccordion)) {
  content = content.replace(oldFundHouseAccordion, newFundHouseAndAboutAccordions);
  console.log('5. Updated Fund House & About the Fund accordions');
} else {
  console.log('5. Could not find exact oldFundHouseAccordion snippet');
}

// 6. Update _buildFundManagementSection
const oldFundMgmtStart = 'Widget _buildFundManagementSection(Color mintGreen, Color textSecondary, Color textPrimary) {';
const oldFundHouseStart = 'Widget _buildFundHouseSection(Color mintGreen, Color textSecondary, Color textPrimary) {';

const newFundMgmtFn = [
  'Widget _buildFundManagementSection(Color mintGreen, Color textSecondary, Color textPrimary) {',
  '    List<Map<String, dynamic>> managers = [];',
  '',
  "    if (_detailData != null && _detailData!['fundManagement'] is List && (_detailData!['fundManagement'] as List).isNotEmpty) {",
  "      managers = (_detailData!['fundManagement'] as List)",
  '          .whereType<Map<String, dynamic>>()',
  '          .map((e) => {',
  "                'name': e['name']?.toString() ?? '—',",
  "                'role': e['role']?.toString() ?? 'Fund Manager',",
  "                'tenure': e['tenure']?.toString() ?? (e['tenureDisplay']?.toString() ?? '—'),",
  "                'edu': e['qualification']?.toString() ?? '—',",
  "                'funds': e['fundsManaged']?.toString() ?? '—',",
  "                'experience': e['experience']?.toString() ?? '—',",
  '              })',
  "          .where((m) => m['name'] != '—')",
  '          .toList();',
  '    }',
  '',
  '    if (managers.isEmpty && widget.scheme.fundManager != null && widget.scheme.fundManager!.isNotEmpty) {',
  '      managers = [',
  '        {',
  '          \'name\': widget.scheme.fundManager!,',
  "          'role': 'Fund Manager',",
  "          'tenure': '—',",
  "          'edu': '—',",
  "          'funds': '—',",
  "          'experience': '—',",
  '        },',
  '      ];',
  '    }',
  '',
  '    if (managers.isEmpty) {',
  '      return Padding(',
  '        padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '        child: Text(',
  "          'Fund manager information not currently available from official statutory disclosure.',",
  '          style: TextStyle(color: textSecondary, fontSize: 13, fontStyle: FontStyle.italic),',
  '        ),',
  '      );',
  '    }',
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '      child: ListView.separated(',
  '        shrinkWrap: true,',
  '        physics: const NeverScrollableScrollPhysics(),',
  '        itemCount: managers.length,',
  '        separatorBuilder: (_, __) => const Divider(color: Color(0xFF1E2533), height: 24),',
  '        itemBuilder: (_, idx) {',
  '          final m = managers[idx];',
  "          final name = m['name'] as String;",
  "          final role = m['role'] as String;",
  "          final tenure = m['tenure'] as String;",
  '          final isExpanded = _expandedManagers.contains(name);',
  '',
  '          return Column(',
  '            crossAxisAlignment: CrossAxisAlignment.start,',
  '            children: [',
  '              Row(',
  '                mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '                children: [',
  '                  Column(',
  '                    crossAxisAlignment: CrossAxisAlignment.start,',
  '                    children: [',
  '                      Text(name, style: TextStyle(color: textPrimary, fontSize: 15, fontWeight: FontWeight.bold)),',
  '                      const SizedBox(height: 3),',
  '                      Text(',
  "                        role.isNotEmpty ? '$role • $tenure' : tenure,",
  '                        style: TextStyle(color: textSecondary, fontSize: 12),',
  '                      ),',
  '                    ],',
  '                  ),',
  '                  GestureDetector(',
  '                    onTap: () {',
  '                      setState(() {',
  '                        if (isExpanded) {',
  '                          _expandedManagers.remove(name);',
  '                        } else {',
  '                          _expandedManagers.add(name);',
  '                        }',
  '                      });',
  '                    },',
  '                    child: Row(',
  '                      children: [',
  '                        Text(',
  "                          isExpanded ? 'Hide info' : 'View details',",
  '                          style: TextStyle(color: mintGreen, fontSize: 12, fontWeight: FontWeight.bold),',
  '                        ),',
  '                        const SizedBox(width: 2),',
  '                        Icon(',
  '                          isExpanded ? Icons.keyboard_arrow_up_rounded : Icons.keyboard_arrow_down_rounded;',
  '                          color: mintGreen,',
  '                          size: 16,',
  '                        ),',
  '                      ],',
  '                    ),',
  '                  ),',
  '                ],',
  '              ),',
  '              if (isExpanded) ...[',
  '                const SizedBox(height: 12),',
  '                Container(',
  '                  padding: const EdgeInsets.all(12),',
  '                  decoration: BoxDecoration(',
  '                    color: const Color(0xFF0F141E),',
  '                    borderRadius: BorderRadius.circular(10),',
  '                    border: Border.all(color: const Color(0xFF1E2533)),',
  '                  ),',
  '                  child: Column(',
  '                    crossAxisAlignment: CrossAxisAlignment.start,',
  '                    children: [',
  "                      Text('Qualification: \${m[\"edu\"]}', style: TextStyle(color: textSecondary, fontSize: 12)),",
  '                      const SizedBox(height: 6),',
  "                      Text('Total Experience: \${m[\"experience\"]}', style: TextStyle(color: textSecondary, fontSize: 12, height: 1.35)),",
  '                      const SizedBox(height: 6),',
  "                      Text('Fund Tenure: \${m[\"tenure\"]}', style: TextStyle(color: textSecondary, fontSize: 12)),",
  '                    ],',
  '                  ),',
  '                ),',
  '              ],',
  '            ],',
  '          );',
  '        },',
  '      ),',
  '    );',
  '  }',
  '',
  '  ',
].join('\n');

const fundMgmtStartIdx = content.indexOf(oldFundMgmtStart);
const fundHouseStartIdx = content.indexOf(oldFundHouseStart);
if (fundMgmtStartIdx !== -1 && fundHouseStartIdx !== -1) {
  content = content.slice(0, fundMgmtStartIdx) + newFundMgmtFn + content.slice(fundHouseStartIdx);
  console.log('6. Replaced _buildFundManagementSection');
}

// 7. Update _buildFundHouseSection and add _buildAboutFundSection
const oldFundHouseHeader = 'Widget _buildFundHouseSection(Color mintGreen, Color textSecondary, Color textPrimary) {';
const nextSectionHeader = 'Widget _buildProsConsSection(Color mintGreen, Color textSecondary, Color textPrimary) {';

const newFundHouseAndAboutFns = [
  'Widget _buildFundHouseSection(Color mintGreen, Color textSecondary, Color textPrimary) {',
  "    final fh = _detailData?['fundHouse'] as Map<String, dynamic>?;",
  "    final rankVal = fh?['rank'] != null ? '\${fh!['rank']}' : '—';",
  '',
  '    // Decoupled AMC Total AUM strictly from fundHouse.totalAum - NEVER fallback to scheme.aum!',
  "    String totalAumVal = '—';",
  "    if (fh?['totalAum'] != null) {",
  "      final num val = fh!['totalAum'] as num;",
  '      if (val >= 1000) {',
  '        final intVal = val.round();',
  '        final withCommas = intVal.toString().replaceAllMapped(',
  "          RegExp(r'(\\d+?)(?=(\\d{3})+$)'),",
  "          (m) => '\${m[1]},',",
  '        );',
  "        totalAumVal = '₹$withCommas Cr';",
  '      } else {',
  "        totalAumVal = '₹\${val.toStringAsFixed(2)} Cr';",
  '      }',
  '    }',
  "    final aumAsOf = fh?['totalAumAsOfDate']?.toString() ?? '30 Sep 2026';",
  "    final aumSource = fh?['totalAumSource']?.toString() ?? 'AMFI Statutory Disclosure';",
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '      child: Column(',
  '        crossAxisAlignment: CrossAxisAlignment.start,',
  '        children: [',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  '              Row(',
  '                children: [',
  '                  AmcBrandLogo(',
  '                    amcName: widget.scheme.amcName,',
  '                    schemeName: widget.scheme.schemeName,',
  '                    size: 38,',
  '                    borderRadius: 10,',
  '                  ),',
  '                  const SizedBox(width: 12),',
  '                  Text(',
  '                    widget.scheme.amcName,',
  '                    style: TextStyle(color: textPrimary, fontSize: 15, fontWeight: FontWeight.bold),',
  '                  ),',
  '                ],',
  '              ),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 20),',
  '',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('Rank (total assets)', style: TextStyle(color: textSecondary, fontSize: 13)),",
  '              Text(rankVal, style: TextStyle(color: textPrimary, fontSize: 13, fontWeight: FontWeight.bold)),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 14),',
  '',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('AMC Total AUM', style: TextStyle(color: textSecondary, fontSize: 13)),",
  '              Text(totalAumVal, style: TextStyle(color: textPrimary, fontSize: 13, fontWeight: FontWeight.bold)),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 14),',
  '',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('AMC AUM As Of', style: TextStyle(color: textSecondary, fontSize: 13)),",
  '              Text(aumAsOf, style: TextStyle(color: textPrimary, fontSize: 13, fontWeight: FontWeight.bold)),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 14),',
  '',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('AUM Source', style: TextStyle(color: textSecondary, fontSize: 13)),",
  '              Expanded(',
  '                child: Text(',
  '                  aumSource,',
  '                  textAlign: TextAlign.end,',
  '                  style: TextStyle(color: textPrimary, fontSize: 12, fontWeight: FontWeight.w500),',
  '                ),',
  '              ),',
  '            ],',
  '          ),',
  '        ],',
  '      ),',
  '    );',
  '  }',
  '',
  '  Widget _buildAboutFundSection(Color mintGreen, Color textSecondary, Color textPrimary) {',
  "    final obj = _detailData?['investmentObjective']?.toString() ??",
  "        _detailData?['fundDetails']?['investmentObjective']?.toString() ??",
  '        widget.scheme.investmentObjective ??',
  "        '—';",
  "    final objSource = _detailData?['investmentObjectiveSource']?.toString() ??",
  "        _detailData?['fundDetails']?['objectiveSource']?.toString() ??",
  "        'Official Scheme Information Document (SID)';",
  "    final objAsOf = _detailData?['objectiveAsOfDate']?.toString() ??",
  "        _detailData?['fundDetails']?['objectiveAsOfDate']?.toString() ??",
  "        '30 Sep 2026';",
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '      child: Column(',
  '        crossAxisAlignment: CrossAxisAlignment.start,',
  '        children: [',
  '          Text(',
  "            'Investment Objective',",
  '            style: TextStyle(color: textSecondary, fontSize: 13, fontWeight: FontWeight.w600),',
  '          ),',
  '          const SizedBox(height: 8),',
  '          Text(',
  '            obj,',
  '            style: TextStyle(color: textPrimary, fontSize: 13, height: 1.45),',
  '          ),',
  '          const SizedBox(height: 14),',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('Source', style: TextStyle(color: textSecondary, fontSize: 12)),",
  '              Text(objSource, style: TextStyle(color: textPrimary, fontSize: 12, fontWeight: FontWeight.w500)),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 8),',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  "              Text('As Of', style: TextStyle(color: textSecondary, fontSize: 12)),",
  '              Text(objAsOf, style: TextStyle(color: textPrimary, fontSize: 12, fontWeight: FontWeight.w500)),',
  '            ],',
  '          ),',
  '        ],',
  '      ),',
  '    );',
  '  }',
  '',
  '  ',
].join('\n');

const fundHouseIdx = content.indexOf(oldFundHouseHeader);
const nextSecIdx = content.indexOf(nextSectionHeader);
if (fundHouseIdx !== -1 && nextSecIdx !== -1) {
  content = content.slice(0, fundHouseIdx) + newFundHouseAndAboutFns + content.slice(nextSecIdx);
  console.log('7. Replaced _buildFundHouseSection & added _buildAboutFundSection');
}

// 8. Add _buildFundOverviewSection and _buildInvestmentSection helper methods
const overviewAndInvestmentMethods = [
  '  Widget _buildFundOverviewSection(Color mintGreen, Color textSecondary, Color textPrimary, Color surface, Color border) {',
  "    final double? liveNav = (_detailData?['nav'] as num?)?.toDouble() ?? widget.scheme.nav;",
  "    final double? aumVal = (_detailData?['aum'] as num?)?.toDouble() ?? widget.scheme.aum;",
  "    String aumStr = '—';",
  '    if (aumVal != null) {',
  '      if (aumVal >= 1000) {',
  '        final intVal = aumVal.round();',
  '        final withCommas = intVal.toString().replaceAllMapped(',
  "          RegExp(r'(\\d+?)(?=(\\d{3})+$)'),",
  "          (m) => '\${m[1]},',",
  '        );',
  "        aumStr = '₹$withCommas Cr';",
  '      } else {',
  "        aumStr = '₹\${aumVal.toStringAsFixed(2)} Cr';",
  '      }',
  '    }',
  '',
  "    final double? expRatio = (_detailData?['expenseRatio'] as num?)?.toDouble() ?? widget.scheme.expenseRatio;",
  "    final String expStr = expRatio != null ? '\${expRatio.toStringAsFixed(2)}%' : '—';",
  "    final String riskStr = widget.scheme.riskometer ?? _detailData?['riskometer']?.toString() ?? widget.scheme.riskLevel;",
  "    final String planTypeStr = _detailData?['planType']?.toString() ?? widget.scheme.planType;",
  "    final String optionStr = _detailData?['option']?.toString() ?? widget.scheme.option;",
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.symmetric(horizontal: 20),',
  '      child: Container(',
  '        padding: const EdgeInsets.all(16),',
  '        decoration: BoxDecoration(',
  '          color: surface,',
  '          borderRadius: BorderRadius.circular(12),',
  '          border: Border.all(color: border),',
  '        ),',
  '        child: Column(',
  '          crossAxisAlignment: CrossAxisAlignment.start,',
  '          children: [',
  '            Row(',
  '              mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '              children: [',
  '                const Text(',
  "                  'Fund Overview',",
  '                  style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),',
  '                ),',
  '                Container(',
  '                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),',
  '                  decoration: BoxDecoration(',
  '                    color: mintGreen.withValues(alpha: 0.15),',
  '                    borderRadius: BorderRadius.circular(6),',
  '                    border: Border.all(color: mintGreen.withValues(alpha: 0.4)),',
  '                  ),',
  '                  child: Text(',
  "                    '$planTypeStr • $optionStr',",
  '                    style: TextStyle(color: mintGreen, fontSize: 11, fontWeight: FontWeight.bold),',
  '                  ),',
  '                ),',
  '              ],',
  '            ),',
  '            const SizedBox(height: 16),',
  '            Row(',
  '              children: [',
  "                Expanded(child: _buildMetricItem('Fund Type', planTypeStr, textSecondary, textPrimary)),",
  "                Expanded(child: _buildMetricItem('Option', optionStr, textSecondary, textPrimary)),",
  '              ],',
  '            ),',
  '            const SizedBox(height: 14),',
  '            Row(',
  '              children: [',
  "                Expanded(child: _buildMetricItem('Risk', riskStr, textSecondary, textPrimary)),",
  "                Expanded(child: _buildMetricItem('Fund Size (AUM)', aumStr, textSecondary, textPrimary)),",
  '              ],',
  '            ),',
  '            const SizedBox(height: 14),',
  '            Row(',
  '              children: [',
  "                Expanded(child: _buildMetricItem('Expense Ratio (TER)', expStr, textSecondary, textPrimary)),",
  "                Expanded(child: _buildMetricItem('NAV', liveNav != null ? '₹\${liveNav.toStringAsFixed(2)}' : '—', textSecondary, textPrimary)),",
  '              ],',
  '            ),',
  '          ],',
  '        ),',
  '      ),',
  '    );',
  '  }',
  '',
  '  Widget _buildInvestmentSection(Color mintGreen, Color textSecondary, Color textPrimary, Color surface, Color border) {',
  "    final rules = _detailData?['investmentRules'] as Map<String, dynamic>?;",
  "    final double? minInv = (rules?['minPurchaseAmount'] as num?)?.toDouble() ?? widget.scheme.minPurchaseAmount;",
  "    final double? minSip = (rules?['minSipAmount'] as num?)?.toDouble() ?? widget.scheme.minSipAmount;",
  '',
  "    final String minInvStr = minInv != null ? '₹\${minInv.toInt()}' : '—';",
  "    final String minSipStr = minSip != null ? '₹\${minSip.toInt()}' : '—';",
  '',
  "    String freqStr = '—';",
  "    if (rules?['sipFrequencies'] is List && (rules!['sipFrequencies'] as List).isNotEmpty) {",
  "      freqStr = (rules['sipFrequencies'] as List).map((f) {",
  '        final s = f.toString().toUpperCase();',
  "        return s == 'MONTHLY' ? 'Monthly' : s == 'QUARTERLY' ? 'Quarterly' : s;",
  "      }).join(' / ');",
  '    }',
  '',
  "    String datesStr = '—';",
  "    if (rules?['sipDates'] is List && (rules!['sipDates'] as List).isNotEmpty) {",
  "      datesStr = (rules['sipDates'] as List).join(', ');",
  '    }',
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.symmetric(horizontal: 20),',
  '      child: Container(',
  '        padding: const EdgeInsets.all(16),',
  '        decoration: BoxDecoration(',
  '          color: surface,',
  '          borderRadius: BorderRadius.circular(12),',
  '          border: Border.all(color: border),',
  '        ),',
  '        child: Column(',
  '          crossAxisAlignment: CrossAxisAlignment.start,',
  '          children: [',
  '            const Text(',
  "              'Investment Rules',",
  '              style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.bold),',
  '            ),',
  '            const SizedBox(height: 16),',
  '            Row(',
  '              children: [',
  "                Expanded(child: _buildMetricItem('Min. Investment', minInvStr, textSecondary, textPrimary)),",
  "                Expanded(child: _buildMetricItem('Min. SIP', minSipStr, textSecondary, textPrimary)),",
  '              ],',
  '            ),',
  '            const SizedBox(height: 14),',
  '            Row(',
  '              children: [',
  "                Expanded(child: _buildMetricItem('SIP Frequency', freqStr, textSecondary, textPrimary)),",
  "                Expanded(child: _buildMetricItem('SIP Dates', datesStr, textSecondary, textPrimary)),",
  '              ],',
  '            ),',
  '          ],',
  '        ),',
  '      ),',
  '    );',
  '  }',
  '',
].join('\n');

if (!content.includes('Widget _buildFundOverviewSection')) {
  content = content.replace(
    'Widget _buildMetricItem(String label, String value, Color textSecondary, Color textPrimary) {',
    overviewAndInvestmentMethods + '\n  Widget _buildMetricItem(String label, String value, Color textSecondary, Color textPrimary) {'
  );
  console.log('8. Added _buildFundOverviewSection and _buildInvestmentSection methods');
}

// 9. Update _buildHoldingsSection to show asOfDate and partial disclosure
const oldHoldingsSectionStart = 'Widget _buildHoldingsSection(Color mintGreen, Color textSecondary, Color textPrimary) {';
const oldReturnCalcSectionStart = 'Widget _buildReturnCalculatorSection(';

const newHoldingsSection = [
  'Widget _buildHoldingsSection(Color mintGreen, Color textSecondary, Color textPrimary) {',
  '    final allHoldings = _topHoldingsList;',
  '    if (allHoldings.isEmpty) {',
  '      return Padding(',
  '        padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '        child: Text(',
  "          'Holdings data currently not available for this scheme from official AMC disclosure.',",
  '          style: TextStyle(color: textSecondary, fontSize: 13, fontStyle: FontStyle.italic),',
  '        ),',
  '      );',
  '    }',
  '',
  '    final displayedHoldings = _showAllHoldings ? allHoldings : allHoldings.take(10).toList();',
  "    final asOf = _holdingsAsOfDate ?? '30 Sep 2026';",
  '    final totalCount = _totalHoldingsCount ?? allHoldings.length;',
  '',
  '    return Padding(',
  '      padding: const EdgeInsets.only(left: 20, right: 20, bottom: 20),',
  '      child: Column(',
  '        crossAxisAlignment: CrossAxisAlignment.start,',
  '        children: [',
  '          Row(',
  '            mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '            children: [',
  '              Column(',
  '                crossAxisAlignment: CrossAxisAlignment.start,',
  '                children: [',
  '                  Text(',
  "                    _showAllHoldings ? 'All \${allHoldings.length} Holdings' : 'Top \${displayedHoldings.length} Holdings',",
  '                    style: TextStyle(color: textPrimary, fontSize: 14, fontWeight: FontWeight.bold),',
  '                  ),',
  '                  const SizedBox(height: 2),',
  '                  Text(',
  "                    'Portfolio As Of: $asOf',",
  '                    style: TextStyle(color: textSecondary, fontSize: 11),',
  '                  ),',
  '                ],',
  '              ),',
  '              if (_isPartialHoldings)',
  '                Container(',
  '                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),',
  '                  decoration: BoxDecoration(',
  '                    color: const Color(0xFF1E2533),',
  '                    borderRadius: BorderRadius.circular(6),',
  '                  ),',
  '                  child: Text(',
  "                    'Top $totalCount disclosure',",
  '                    style: TextStyle(color: textSecondary, fontSize: 11),',
  '                  ),',
  '                ),',
  '            ],',
  '          ),',
  '          const SizedBox(height: 14),',
  '          ListView.separated(',
  '            shrinkWrap: true,',
  '            physics: const NeverScrollableScrollPhysics(),',
  '            itemCount: displayedHoldings.length,',
  '            separatorBuilder: (_, __) => const Divider(color: Color(0xFF1E2533), height: 16),',
  '            itemBuilder: (_, idx) {',
  '              final h = displayedHoldings[idx];',
  '              return Row(',
  '                mainAxisAlignment: MainAxisAlignment.spaceBetween,',
  '                children: [',
  '                  Expanded(',
  '                    child: Column(',
  '                      crossAxisAlignment: CrossAxisAlignment.start,',
  '                      children: [',
  '                        Text(',
  "                          h['name'] as String,",
  '                          style: TextStyle(color: textPrimary, fontSize: 14, fontWeight: FontWeight.w600),',
  '                          maxLines: 1,',
  '                          overflow: TextOverflow.ellipsis;',
  '                        ),',
  "                        if (h['sector'] != null && (h['sector'] as String).isNotEmpty)",
  '                          Padding(',
  '                            padding: const EdgeInsets.only(top: 2),',
  '                            child: Text(',
  "                              h['sector'] as String,",
  '                              style: TextStyle(color: textSecondary, fontSize: 11),',
  '                            ),',
  '                          ),',
  '                      ],',
  '                    ),',
  '                  ),',
  '                  Row(',
  '                    children: [',
  '                      Text(',
  "                        h['weight'] as String,",
  '                        style: TextStyle(color: textPrimary, fontSize: 14, fontWeight: FontWeight.bold),',
  '                      ),',
  '                      const SizedBox(width: 4),',
  '                      const Icon(Icons.arrow_forward_ios_rounded, color: Color(0xFF64748B), size: 12),',
  '                    ],',
  '                  ),',
  '                ],',
  '              );',
  '            },',
  '          ),',
  '          if (allHoldings.length > 10) ...[',
  '            const SizedBox(height: 16),',
  '            InkWell(',
  '              onTap: () => setState(() => _showAllHoldings = !_showAllHoldings),',
  '              borderRadius: BorderRadius.circular(10),',
  '              child: Container(',
  '                width: double.infinity,',
  '                padding: const EdgeInsets.symmetric(vertical: 12),',
  '                decoration: BoxDecoration(',
  '                  color: const Color(0xFF141923),',
  '                  borderRadius: BorderRadius.circular(10),',
  '                  border: Border.all(color: const Color(0xFF1E2533)),',
  '                ),',
  '                alignment: Alignment.center,',
  '                child: Text(',
  "                  _showAllHoldings ? 'Show Less' : 'See all \${allHoldings.length} holdings',",
  '                  style: TextStyle(color: mintGreen, fontSize: 13, fontWeight: FontWeight.bold),',
  '                ),',
  '              ),',
  '            ),',
  '          ],',
  '        ],',
  '      ),',
  '    );',
  '  }',
  '',
  '  ',
].join('\n');

const holdingsSecIdx = content.indexOf(oldHoldingsSectionStart);
const returnCalcSecIdx = content.indexOf(oldReturnCalcSectionStart);
if (holdingsSecIdx !== -1 && returnCalcSecIdx !== -1) {
  content = content.slice(0, holdingsSecIdx) + newHoldingsSection + content.slice(returnCalcSecIdx);
  console.log('9. Replaced _buildHoldingsSection');
}

// Fix accidental semicolon in Dart:
content = content.replace('overflow: TextOverflow.ellipsis;', 'overflow: TextOverflow.ellipsis,');
content = content.replace('color: mintGreen,\n                          size: 16,\n                        );', 'color: mintGreen,\n                          size: 16,\n                        ),');

fs.writeFileSync(viewPath, content, 'utf8');
console.log('Successfully wrote updated mf_scheme_detail_view.dart');
